---
name: main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  shared-storage:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - DOCKERI: rockylinux:9
            DBTYPE: PG
            DBVERSION: 16
            CLNAME: ro9pg
            EXTRA_VARS: "pgbackrest_excpected_release=2.53.1 check_pgbackrest_build=true"

    steps:
      - uses: actions/checkout@v4
        with:
          path: check_pgbackrest
      - uses: shogo82148/actions-setup-perl@v1

      - name: Initial step
        run: cd ${HOME?} && sh ${GITHUB_WORKSPACE?}/check_pgbackrest/tests/run.sh -i

      - name: Run CI script
        env:
          ARCH: shared-storage
          CLPATH: /home/runner/clusters
          CLNAME: ${{ matrix.CLNAME }}
          DBTYPE: ${{ matrix.DBTYPE }}
          DBVERSION: ${{ matrix.DBVERSION }}
          DOCKERI: ${{ matrix.DOCKERI }}
          EXTRA_VARS: ${{ matrix.EXTRA_VARS }}
          RUN_ARGS:
          ACTIVITY: true
        run: cd ${HOME?} && sh ${GITHUB_WORKSPACE?}/check_pgbackrest/tests/ci.sh

  with-repo-host:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - DOCKERI: ubuntu:22.04
            DBTYPE: PG
            DBVERSION: 16
            CLNAME: u22pg
            EXTRA_VARS: "pgbackrest_excpected_release=2.53.1 check_pgbackrest_build=true"

    steps:
      - uses: actions/checkout@v4
        with:
          path: check_pgbackrest
      - uses: shogo82148/actions-setup-perl@v1

      - name: Initial step
        run: cd ${HOME?} && sh ${GITHUB_WORKSPACE?}/check_pgbackrest/tests/run.sh -i

      - name: Run CI script
        env:
          ARCH: with-repo-host
          CLPATH: /home/runner/clusters
          CLNAME: ${{ matrix.CLNAME }}
          DBTYPE: ${{ matrix.DBTYPE }}
          DBVERSION: ${{ matrix.DBVERSION }}
          DOCKERI: ${{ matrix.DOCKERI }}
          EXTRA_VARS: ${{ matrix.EXTRA_VARS }}
          RUN_ARGS:
          ACTIVITY: true
        run: cd ${HOME?} && sh ${GITHUB_WORKSPACE?}/check_pgbackrest/tests/ci.sh
